### ISSUE TITLE
What's your favorite project on GitHub and why?

### ISSUE THREAD

**Issue by sindresorhus** [honglio/ama#2]

**Comment by honglio** [comment]
[impress.js](https://github.com/impress/impress.js), I build my project based on this project.
jQuery, It has the most stars.
[streisand](https://github.com/jlund/streisand), I need it to cross the GFW.
[fastclick](https://github.com/ftlabs/fastclick), Help to conquer the 300ms delay issue on mobile browser, although not 100% promise, but well tested. 
[pm2](https://github.com/Unitech/pm2), Help me run my Node.js applications on production server without the pain to setup a load balancer.
