### ISSUE TITLE
What does your problem-solving routine look like?

### ISSUE THREAD

**Issue by CarlMungazi** [honglio/ama#5]

**Comment by honglio** [comment]
1. Analysis - what's the field of this problem? can I fix it by myself or need help? Is this problem need to be fixed urgently? How long can I fixed it?
2. Prioritization - critical? important? normal? minor?
3. Reasoning - using web inspect like weinre, chrome inspector or safari inspector.
4. Offer a solution - google or yandex to gether some solutions.
5. Choose a solution from step 4. and Implement on local developing environment.
6. Compare the result. If problem doesn't fixed, back to step 5.
7. If all the solution has been tried, and the problem remains, back to step 4.
8. If done step 4-7 twice, back to step 3.
9. If can't get this work done within the agreed time, back to step 1.
